name: "test Actions"

on:
  workflow_dispatch:
    inputs:
      grid-args:
        required: true
        default: --config config.yml --instance_type t2.medium
        description: test actions
        # make sure name is not longer than this
        run_name:
        required: false
        default: "c$(date '+%y%m%d-%H%M%S')"
        type: string

jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
              
      - id: gridai-obj-status
        run: |
          # failed can flipped to running.  check 3 times for flip flop.
          pwd
          ls -al
          grid run ${{github.event.inputs.grid-args}} hello.py
          export run_name=${{ inputs.run_name }}
          echo "run_name=${run_name}" >> $GITHUB_ENV
        shell: bash
