name: "test Actions"

on:
  workflow_dispatch:
    inputs:
      run_name:
        required: false
        default: c$(date '+%y%m%d-%H%M%S')
        description: Grid.ai Run name`
      grid-args:
        required: true
        default: --config config.yml --instance_type t2.medium
        description: test actions

jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    name: grid-env run
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
              
      - id: gridai-obj-status
        run: |
          # failed can flipped to running.  check 3 times for flip flop.
          pwd
          ls -al
          grid run ${{github.event.inputs.grid-args}} run.py
          export run_name=${{ inputs.run_name }}
          echo "run_name=${run_name}" >> $GITHUB_ENV
          echo "run_name: ${run_name}"
          grid logs --show-build-logs ${run_name}-exp0
        shell: bash
      - uses: robert-s-lee/actions@main
        with:
          obj_type: run 
          obj_id: ${{ steps.run.outputs.run_name }}
      - run: |
          echo echo "run_name: ${env.run_name}-exp0"
          grid logs --show-build-logs ${{ env.run_name }}-exp0
          
