name: "test Actions"

on:
  workflow_dispatch:
    inputs:
      run_name:
        required: false
        default:  "c$(date '+%y%m%d-%H%M%S')"
        type: string
      grid-args:
        required: true
        default: --config config.yml --instance_type t2.medium
        description: test actions

jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}            
      - run: |
          # failed can flipped to running.  check 3 times for flip flop.
          grid run ${{github.event.inputs.grid-args}} run.py | tee  grid.run.log
      - run: |
          ls -al grid.run.log
          echo The RunName is ${{ github.event.inputs.run_name }}
          echo EXP_NAME= "${{ github.event.inputs.run_name }}-exp0"           
          if [[ -z "${run_name}" ]]; then
            echo "Error: 'grid_name:[run_name]' not found in output"
            exit 1
          fi 
      - id: grid-status
        uses: gridai-actions/gridai-status@v0
        with:
          obj-type: run
          obj-id: ${run_name}
